namespace Microsoft.Web.WebView2.Core.Raw;

public enum COREWEBVIEW2_KEY_EVENT_KIND
{
    COREWEBVIEW2_KEY_EVENT_KIND_KEY_DOWN,
    COREWEBVIEW2_KEY_EVENT_KIND_KEY_UP,
    COREWEBVIEW2_KEY_EVENT_KIND_SYSTEM_KEY_DOWN,
    COREWEBVIEW2_KEY_EVENT_KIND_SYSTEM_KEY_UP
}
