using System.Runtime.CompilerServices;

namespace Microsoft.Web.WebView2.Core.Raw;

[CompilerGenerated]
//[TypeIdentifier("26D34152-879F-4065-BEA2-3DAA2CFADFB8", "Microsoft.Web.WebView2.Core.Raw.COREWEBVIEW2_MOVE_FOCUS_REASON")]
public enum COREWEBVIEW2_MOVE_FOCUS_REASON
{
    COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC,
    COREWEBVIEW2_MOVE_FOCUS_REASON_NEXT,
    COREWEBVIEW2_MOVE_FOCUS_REASON_PREVIOUS
}
