namespace Microsoft.Web.WebView2.Core.Raw;

public enum COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT
{
    COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT_PNG,
    COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT_JPEG
}
