using Microsoft.CodeAnalysis;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace WinFormsComInterop.SourceGenerator.Tests
{
    [TestClass]
    public class ProxyCreationTest : CodeGenerationTestBase
    {
        [TestMethod]
        public void DeclarationOfProxy()
        {
            string source = @"
namespace Foo
{
    using System.Threading;

    public interface IStr
    {
        void Read(byte* pv, uint cb, uint* pcbRead);
    }

    [ComProxy(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using ComInterfaceDispatch = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    partial unsafe class IStrProxy
    {
        [System.Runtime.InteropServices.UnmanagedCallersOnly]
        public static int Read(System.IntPtr thisPtr, byte* pv, uint cb, uint* pcbRead)
        {
            try
            {
                var inst = ComInterfaceDispatch.GetInstance<global::Foo.IStr>((ComInterfaceDispatch*)thisPtr);
                inst.Read(pv, cb, pcbRead);
            }
            catch (System.Exception __e)
            {
                return __e.HResult;
            }

            return 0; // S_OK;
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void MethodWithoutParameters()
        {
            string source = @"
namespace Foo
{
    using System.Threading;

    public interface ICloneable
    {
        void Clone();
    }

    [ComProxy(typeof(ICloneable))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using ComInterfaceDispatch = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    partial unsafe class ICloneableProxy
    {
        [System.Runtime.InteropServices.UnmanagedCallersOnly]
        public static int Clone(System.IntPtr thisPtr)
        {
            try
            {
                var inst = ComInterfaceDispatch.GetInstance<global::Foo.ICloneable>((ComInterfaceDispatch*)thisPtr);
                inst.Clone();
            }
            catch (System.Exception __e)
            {
                return __e.HResult;
            }

            return 0; // S_OK;
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        [Ignore]
        public void ExternIntefaceType()
        {
            string source = @"
extern alias drawing;
namespace Foo
{
    using System.Threading;

    public interface ICloneable
    {
        void Clone();
    }

    [ComProxy(typeof(ICloneable))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using ComInterfaceDispatch = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    partial unsafe class ICloneableProxy
    {
        [System.Runtime.InteropServices.UnmanagedCallersOnly]
        public static int Clone(System.IntPtr thisPtr)
        {
            try
            {
                var inst = ComInterfaceDispatch.GetInstance<Foo.ICloneable>((ComInterfaceDispatch*)thisPtr);
                inst.Clone();
            }
            catch (System.Exception __e)
            {
                return __e.HResult;
            }

            return 0; // S_OK;
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void EnumParameters()
        {
            string source = @"
namespace Foo
{
    using System.Threading;

    enum EnumValue {}

    public interface IStr
    {
        void Read(byte* pv, EnumValue cb, uint* pcbRead);
    }

    [ComProxy(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using ComInterfaceDispatch = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    partial unsafe class IStrProxy
    {
        [System.Runtime.InteropServices.UnmanagedCallersOnly]
        public static int Read(System.IntPtr thisPtr, byte* pv, int cb, uint* pcbRead)
        {
            try
            {
                var inst = ComInterfaceDispatch.GetInstance<global::Foo.IStr>((ComInterfaceDispatch*)thisPtr);
                inst.Read(pv, (global::Foo.EnumValue)cb, pcbRead);
            }
            catch (System.Exception __e)
            {
                return __e.HResult;
            }

            return 0; // S_OK;
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void ComInterfaceParameter()
        {
            string source = @"
namespace Foo
{
    using System.Threading;

    enum EnumValue {}

    public interface IStr
    {
        void CopyTo(IStr pstm, ulong cb);
    }

    [ComProxy(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using ComInterfaceDispatch = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    partial unsafe class IStrProxy
    {
        [System.Runtime.InteropServices.UnmanagedCallersOnly]
        public static int CopyTo(System.IntPtr thisPtr, System.IntPtr pstm, ulong cb)
        {
            try
            {
                var inst = ComInterfaceDispatch.GetInstance<global::Foo.IStr>((ComInterfaceDispatch*)thisPtr);
                var local_0 = ComInterfaceDispatch.GetInstance<global::Foo.IStr>((ComInterfaceDispatch*)pstm);
                inst.CopyTo(local_0, cb);
            }
            catch (System.Exception __e)
            {
                return __e.HResult;
            }

            return 0; // S_OK;
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void ObjectParameter()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    enum EnumValue {}

    public interface IStr
    {
        void CopyTo([MarshalAs(UnmanagedType.Interface)]object data, ulong cb);
    }

    [ComProxy(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using ComInterfaceDispatch = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    partial unsafe class IStrProxy
    {
        [System.Runtime.InteropServices.UnmanagedCallersOnly]
        public static int CopyTo(System.IntPtr thisPtr, System.IntPtr data, ulong cb)
        {
            try
            {
                var inst = ComInterfaceDispatch.GetInstance<global::Foo.IStr>((ComInterfaceDispatch*)thisPtr);
                var local_0 = ComInterfaceDispatch.GetInstance<object>((ComInterfaceDispatch*)data);
                inst.CopyTo(local_0, cb);
            }
            catch (System.Exception __e)
            {
                return __e.HResult;
            }

            return 0; // S_OK;
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void OutParameter()
        {
            string source = @"
namespace Foo
{
    using System.Threading;

    enum STATFLAG {}
    struct STATSTG { int Dummy; }

    public interface IStr
    {
        void Stat(out STATSTG pstatstg, STATFLAG grfStatFlag);
    }

    [ComProxy(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using ComInterfaceDispatch = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    partial unsafe class IStrProxy
    {
        [System.Runtime.InteropServices.UnmanagedCallersOnly]
        public static int Stat(System.IntPtr thisPtr, global::Foo.STATSTG* pstatstg, int grfStatFlag)
        {
            try
            {
                var inst = ComInterfaceDispatch.GetInstance<global::Foo.IStr>((ComInterfaceDispatch*)thisPtr);
                inst.Stat(out *pstatstg, (global::Foo.STATFLAG)grfStatFlag);
            }
            catch (System.Exception __e)
            {
                return __e.HResult;
            }

            return 0; // S_OK;
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void RefParameter()
        {
            string source = @"
namespace Foo
{
    using System.Threading;

    enum STATFLAG {}
    struct STATSTG { int Dummy; }

    public interface IStr
    {
        void Stat(ref STATSTG pstatstg, STATFLAG grfStatFlag);
    }

    [ComProxy(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using ComInterfaceDispatch = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    partial unsafe class IStrProxy
    {
        [System.Runtime.InteropServices.UnmanagedCallersOnly]
        public static int Stat(System.IntPtr thisPtr, global::Foo.STATSTG* pstatstg, int grfStatFlag)
        {
            try
            {
                var inst = ComInterfaceDispatch.GetInstance<global::Foo.IStr>((ComInterfaceDispatch*)thisPtr);
                inst.Stat(ref *pstatstg, (global::Foo.STATFLAG)grfStatFlag);
            }
            catch (System.Exception __e)
            {
                return __e.HResult;
            }

            return 0; // S_OK;
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void InParameter()
        {
            string source = @"
namespace Foo
{
    using System.Threading;

    enum STATFLAG {}
    struct STATSTG { int Dummy; }

    public interface IStr
    {
        void Stat(in STATSTG pstatstg, STATFLAG grfStatFlag);
    }

    [ComProxy(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using ComInterfaceDispatch = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    partial unsafe class IStrProxy
    {
        [System.Runtime.InteropServices.UnmanagedCallersOnly]
        public static int Stat(System.IntPtr thisPtr, global::Foo.STATSTG* pstatstg, int grfStatFlag)
        {
            try
            {
                var inst = ComInterfaceDispatch.GetInstance<global::Foo.IStr>((ComInterfaceDispatch*)thisPtr);
                inst.Stat(in *pstatstg, (global::Foo.STATFLAG)grfStatFlag);
            }
            catch (System.Exception __e)
            {
                return __e.HResult;
            }

            return 0; // S_OK;
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void PreserveSig()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    enum HRESULT {}

    public interface IStr
    {
        [PreserveSig]
        HRESULT LockRegion(ulong libOffset);
    }

    [ComProxy(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using ComInterfaceDispatch = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    partial unsafe class IStrProxy
    {
        [System.Runtime.InteropServices.UnmanagedCallersOnly]
        public static int LockRegion(System.IntPtr thisPtr, ulong libOffset)
        {
            try
            {
                var inst = ComInterfaceDispatch.GetInstance<global::Foo.IStr>((ComInterfaceDispatch*)thisPtr);
                return (int)inst.LockRegion(libOffset);
            }
            catch (System.Exception __e)
            {
                return __e.HResult;
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void ReturnValue()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    enum HRESULT {}

    public interface IStr
    {
        IStr Clone();
    }

    [ComProxy(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using ComInterfaceDispatch = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    partial unsafe class IStrProxy
    {
        [System.Runtime.InteropServices.UnmanagedCallersOnly]
        public static int Clone(System.IntPtr thisPtr, System.IntPtr* retVal)
        {
            try
            {
                var inst = ComInterfaceDispatch.GetInstance<global::Foo.IStr>((ComInterfaceDispatch*)thisPtr);
                *retVal = Marshal.GetIUnknownForObject(inst.Clone());
            }
            catch (System.Exception __e)
            {
                return __e.HResult;
            }

            return 0; // S_OK;
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void GetProperty()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    enum HRESULT {}

    public interface IStr
    {
        IStr Parent { get; }
    }

    [ComProxy(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using ComInterfaceDispatch = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    partial unsafe class IStrProxy
    {
        [System.Runtime.InteropServices.UnmanagedCallersOnly]
        public static int get_Parent(System.IntPtr thisPtr, System.IntPtr* retVal)
        {
            try
            {
                var inst = ComInterfaceDispatch.GetInstance<global::Foo.IStr>((ComInterfaceDispatch*)thisPtr);
                *retVal = Marshal.GetIUnknownForObject(inst.Parent);
            }
            catch (System.Exception __e)
            {
                return __e.HResult;
            }

            return 0; // S_OK;
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }
    }
}
