using Microsoft.CodeAnalysis;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace WinFormsComInterop.SourceGenerator.Tests
{
    [TestClass]
    public class RuntimeCallableWrapperTest : CodeGenerationTestBase
    {
        [TestMethod]
        public void DeclarationOfProxy()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        void Read(byte* pv, uint cb, uint* pcbRead);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        void global::Foo.IStr.Read(byte* pv, uint cb, uint* pcbRead)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            try
            {
                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                result = ((delegate* unmanaged<System.IntPtr, byte*, uint, uint*, int>)vtbl[3])(thisPtr, pv, cb, pcbRead);
                if (result != 0)
                {
                    Marshal.ThrowExceptionForHR(result);
                }

            }
            finally
            {
                Marshal.Release(thisPtr);
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void EnumParameter()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum SeekOrigin {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        void Seek(long dlibMove, SeekOrigin dwOrigin, ulong* plibNewPosition);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        void global::Foo.IStr.Seek(long dlibMove, global::Foo.SeekOrigin dwOrigin, ulong* plibNewPosition)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            try
            {
                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                result = ((delegate* unmanaged<System.IntPtr, long, int, ulong*, int>)vtbl[3])(thisPtr, dlibMove, (int)dwOrigin, plibNewPosition);
                if (result != 0)
                {
                    Marshal.ThrowExceptionForHR(result);
                }

            }
            finally
            {
                Marshal.Release(thisPtr);
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void EnumOutParameter()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum SeekOrigin {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        void Seek(long dlibMove, out SeekOrigin dwOrigin, ulong* plibNewPosition);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        void global::Foo.IStr.Seek(long dlibMove, out global::Foo.SeekOrigin dwOrigin, ulong* plibNewPosition)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            try
            {
                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                int local_1;
                result = ((delegate* unmanaged<System.IntPtr, long, int*, ulong*, int>)vtbl[3])(thisPtr, dlibMove, &local_1, plibNewPosition);
                if (result != 0)
                {
                    Marshal.ThrowExceptionForHR(result);
                }

                dwOrigin = (global::Foo.SeekOrigin)local_1;
            }
            finally
            {
                Marshal.Release(thisPtr);
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void ComInterfaceParameter()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum SeekOrigin {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        void CopyTo(IStr pstm, ulong cb, ulong* pcbRead, ulong* pcbWritten);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        void global::Foo.IStr.CopyTo(global::Foo.IStr pstm, ulong cb, ulong* pcbRead, ulong* pcbWritten)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            try
            {
                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                System.IntPtr local_0;
                if (pstm == null)
                {
                    local_0 = System.IntPtr.Zero;
                }
                else
                {
                    var local_0_unk = MarshalSupport.GetIUnknownForObject(pstm);
                    var local_pstm_IID = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
                    result = Marshal.QueryInterface(local_0_unk, ref local_pstm_IID, out local_0);
                    if (result != 0)
                    {
                        Marshal.ThrowExceptionForHR(result);
                    }
                }

                result = ((delegate* unmanaged<System.IntPtr, System.IntPtr, ulong, ulong*, ulong*, int>)vtbl[3])(thisPtr, local_0, cb, pcbRead, pcbWritten);
                if (result != 0)
                {
                    Marshal.ThrowExceptionForHR(result);
                }

            }
            finally
            {
                Marshal.Release(thisPtr);
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void EnumReturn()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum SeekOrigin {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        SeekOrigin CopyTo(IStr pstm, ulong cb, ulong* pcbRead, ulong* pcbWritten);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        global::Foo.SeekOrigin global::Foo.IStr.CopyTo(global::Foo.IStr pstm, ulong cb, ulong* pcbRead, ulong* pcbWritten)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            try
            {
                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                System.IntPtr local_0;
                if (pstm == null)
                {
                    local_0 = System.IntPtr.Zero;
                }
                else
                {
                    var local_0_unk = MarshalSupport.GetIUnknownForObject(pstm);
                    var local_pstm_IID = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
                    result = Marshal.QueryInterface(local_0_unk, ref local_pstm_IID, out local_0);
                    if (result != 0)
                    {
                        Marshal.ThrowExceptionForHR(result);
                    }
                }

                int retVal;
                result = ((delegate* unmanaged<System.IntPtr, System.IntPtr, ulong, ulong*, ulong*, int*, int>)vtbl[3])(thisPtr, local_0, cb, pcbRead, pcbWritten, &retVal);
                if (result != 0)
                {
                    Marshal.ThrowExceptionForHR(result);
                }

                return (global::Foo.SeekOrigin)retVal;
            }
            finally
            {
                Marshal.Release(thisPtr);
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void PreserveSig()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum HRESULT {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        [PreserveSig]
        HRESULT GetWindow(System.IntPtr* phwnd);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        global::Foo.HRESULT global::Foo.IStr.GetWindow(global::System.IntPtr* phwnd)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            try
            {
                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                int retVal;
                retVal = ((delegate* unmanaged<System.IntPtr, global::System.IntPtr*, int>)vtbl[3])(thisPtr, phwnd);
                return (global::Foo.HRESULT)retVal;
            }
            finally
            {
                Marshal.Release(thisPtr);
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void PreserveSigFloat()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum HRESULT {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        [PreserveSig]
        float GetWindow(System.IntPtr* phwnd);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        float global::Foo.IStr.GetWindow(global::System.IntPtr* phwnd)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            try
            {
                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                float retVal;
                retVal = ((delegate* unmanaged<System.IntPtr, global::System.IntPtr*, float>)vtbl[3])(thisPtr, phwnd);
                return (float)retVal;
            }
            finally
            {
                Marshal.Release(thisPtr);
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void ReturnComInterface()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum HRESULT {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        IStr Clone();
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        global::Foo.IStr global::Foo.IStr.Clone()
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            try
            {
                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                System.IntPtr retVal;
                result = ((delegate* unmanaged<System.IntPtr, System.IntPtr*, int>)vtbl[3])(thisPtr, &retVal);
                if (result != 0)
                {
                    Marshal.ThrowExceptionForHR(result);
                }

                return retVal == System.IntPtr.Zero ? null : (global::Foo.IStr)Marshal.GetObjectForIUnknown(retVal);
            }
            finally
            {
                Marshal.Release(thisPtr);
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void OutParameter()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public struct STATSTG {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        void Stat(out STATSTG pstatstg);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        void global::Foo.IStr.Stat(out global::Foo.STATSTG pstatstg)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            try
            {
                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                fixed (global::Foo.STATSTG* local_0 = &pstatstg)
                result = ((delegate* unmanaged<System.IntPtr, global::Foo.STATSTG*, int>)vtbl[3])(thisPtr, local_0);
                if (result != 0)
                {
                    Marshal.ThrowExceptionForHR(result);
                }

            }
            finally
            {
                Marshal.Release(thisPtr);
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void NoParameters()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum SeekOrigin {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        void CopyTo();
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        void global::Foo.IStr.CopyTo()
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            try
            {
                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                result = ((delegate* unmanaged<System.IntPtr, int>)vtbl[3])(thisPtr);
                if (result != 0)
                {
                    Marshal.ThrowExceptionForHR(result);
                }

            }
            finally
            {
                Marshal.Release(thisPtr);
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void LongReturn()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum SeekOrigin {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        long CopyTo(IStr pstm, ulong cb, ulong* pcbRead, ulong* pcbWritten);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        long global::Foo.IStr.CopyTo(global::Foo.IStr pstm, ulong cb, ulong* pcbRead, ulong* pcbWritten)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            try
            {
                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                System.IntPtr local_0;
                if (pstm == null)
                {
                    local_0 = System.IntPtr.Zero;
                }
                else
                {
                    var local_0_unk = MarshalSupport.GetIUnknownForObject(pstm);
                    var local_pstm_IID = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
                    result = Marshal.QueryInterface(local_0_unk, ref local_pstm_IID, out local_0);
                    if (result != 0)
                    {
                        Marshal.ThrowExceptionForHR(result);
                    }
                }

                long retVal;
                result = ((delegate* unmanaged<System.IntPtr, System.IntPtr, ulong, ulong*, ulong*, long*, int>)vtbl[3])(thisPtr, local_0, cb, pcbRead, pcbWritten, &retVal);
                if (result != 0)
                {
                    Marshal.ThrowExceptionForHR(result);
                }

                return retVal;
            }
            finally
            {
                Marshal.Release(thisPtr);
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void LongProperty()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum SeekOrigin {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        long Height { get; }
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        long global::Foo.IStr.Height
        {
            get
            {
                var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
                var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
                if (result != 0)
                {
                    throw new System.InvalidCastException();
                }

                try
                {
                    var comDispatch = (System.IntPtr*)thisPtr;
                    var vtbl = (System.IntPtr*)comDispatch[0];
                    long retVal;
                    result = ((delegate* unmanaged<System.IntPtr, long*, int>)vtbl[3])(thisPtr, &retVal);
                    if (result != 0)
                    {
                        Marshal.ThrowExceptionForHR(result);
                    }

                    return retVal;
                }
                finally
                {
                    Marshal.Release(thisPtr);
                }
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void LongGetSetProperty()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum SeekOrigin {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        long Height { get; set; }
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        long global::Foo.IStr.Height
        {
            get
            {
                var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
                var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
                if (result != 0)
                {
                    throw new System.InvalidCastException();
                }

                try
                {
                    var comDispatch = (System.IntPtr*)thisPtr;
                    var vtbl = (System.IntPtr*)comDispatch[0];
                    long retVal;
                    result = ((delegate* unmanaged<System.IntPtr, long*, int>)vtbl[3])(thisPtr, &retVal);
                    if (result != 0)
                    {
                        Marshal.ThrowExceptionForHR(result);
                    }

                    return retVal;
                }
                finally
                {
                    Marshal.Release(thisPtr);
                }
            }
            set
            {
                var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
                var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
                if (result != 0)
                {
                    throw new System.InvalidCastException();
                }

                try
                {
                    var comDispatch = (System.IntPtr*)thisPtr;
                    var vtbl = (System.IntPtr*)comDispatch[0];
                    result = ((delegate* unmanaged<System.IntPtr, long, int>)vtbl[4])(thisPtr, value);
                    if (result != 0)
                    {
                        Marshal.ThrowExceptionForHR(result);
                    }

                }
                finally
                {
                    Marshal.Release(thisPtr);
                }
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void LongSetProperty()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum SeekOrigin {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        long Height { set; }
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        long global::Foo.IStr.Height
        {
            set
            {
                var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
                var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
                if (result != 0)
                {
                    throw new System.InvalidCastException();
                }

                try
                {
                    var comDispatch = (System.IntPtr*)thisPtr;
                    var vtbl = (System.IntPtr*)comDispatch[0];
                    result = ((delegate* unmanaged<System.IntPtr, long, int>)vtbl[3])(thisPtr, value);
                    if (result != 0)
                    {
                        Marshal.ThrowExceptionForHR(result);
                    }

                }
                finally
                {
                    Marshal.Release(thisPtr);
                }
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void StringParameter()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum SeekOrigin {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        void Seek(long dlibMove, string dwOrigin, ulong* plibNewPosition);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        void global::Foo.IStr.Seek(long dlibMove, string dwOrigin, ulong* plibNewPosition)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            try
            {
                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                var local_1 = Marshal.StringToCoTaskMemUni(dwOrigin);
                result = ((delegate* unmanaged<System.IntPtr, long, System.IntPtr, ulong*, int>)vtbl[3])(thisPtr, dlibMove, local_1, plibNewPosition);
                if (result != 0)
                {
                    Marshal.ThrowExceptionForHR(result);
                }

                Marshal.FreeCoTaskMem(local_1);
            }
            finally
            {
                Marshal.Release(thisPtr);
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void StringReturn()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum SeekOrigin {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        string CopyTo();
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        string global::Foo.IStr.CopyTo()
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            try
            {
                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                System.IntPtr retVal;
                result = ((delegate* unmanaged<System.IntPtr, System.IntPtr*, int>)vtbl[3])(thisPtr, &retVal);
                if (result != 0)
                {
                    Marshal.ThrowExceptionForHR(result);
                }

                return retVal == System.IntPtr.Zero ? null : (string)Marshal.PtrToStringUni(retVal);
            }
            finally
            {
                Marshal.Release(thisPtr);
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void ObjectAsIUnknownParameter()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum SeekOrigin {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        void CopyTo([MarshalAs(UnmanagedType.Interface)]object pstm, ulong cb, ulong* pcbRead, ulong* pcbWritten);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        void global::Foo.IStr.CopyTo(object pstm, ulong cb, ulong* pcbRead, ulong* pcbWritten)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            try
            {
                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                var local_0 = pstm == null ? System.IntPtr.Zero : MarshalSupport.GetIUnknownForObject(pstm);
                result = ((delegate* unmanaged<System.IntPtr, System.IntPtr, ulong, ulong*, ulong*, int>)vtbl[3])(thisPtr, local_0, cb, pcbRead, pcbWritten);
                if (result != 0)
                {
                    Marshal.ThrowExceptionForHR(result);
                }

            }
            finally
            {
                Marshal.Release(thisPtr);
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void ComInterfaceOutParameter()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum SeekOrigin {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        void CopyTo(out IStr pstm, ulong cb, ulong* pcbRead, ulong* pcbWritten);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        void global::Foo.IStr.CopyTo(out global::Foo.IStr pstm, ulong cb, ulong* pcbRead, ulong* pcbWritten)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            try
            {
                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                System.IntPtr local_0;
                result = ((delegate* unmanaged<System.IntPtr, System.IntPtr*, ulong, ulong*, ulong*, int>)vtbl[3])(thisPtr, &local_0, cb, pcbRead, pcbWritten);
                if (result != 0)
                {
                    Marshal.ThrowExceptionForHR(result);
                }

                pstm = local_0 == System.IntPtr.Zero ? null : (global::Foo.IStr)Marshal.GetObjectForIUnknown(local_0);
            }
            finally
            {
                Marshal.Release(thisPtr);
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void OutStringParameter()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum SeekOrigin {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        void Seek(long dlibMove, out string dwOrigin, ulong* plibNewPosition);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        void global::Foo.IStr.Seek(long dlibMove, out string dwOrigin, ulong* plibNewPosition)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            try
            {
                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                System.IntPtr local_1;
                result = ((delegate* unmanaged<System.IntPtr, long, System.IntPtr*, ulong*, int>)vtbl[3])(thisPtr, dlibMove, &local_1, plibNewPosition);
                if (result != 0)
                {
                    Marshal.ThrowExceptionForHR(result);
                }

                dwOrigin = Marshal.PtrToStringUni(local_1);
            }
            finally
            {
                Marshal.Release(thisPtr);
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void StructParameter()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public struct STATSTG {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        void Stat(STATSTG pstatstg);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        void global::Foo.IStr.Stat(global::Foo.STATSTG pstatstg)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            try
            {
                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                result = ((delegate* unmanaged<System.IntPtr, global::Foo.STATSTG, int>)vtbl[3])(thisPtr, pstatstg);
                if (result != 0)
                {
                    Marshal.ThrowExceptionForHR(result);
                }

            }
            finally
            {
                Marshal.Release(thisPtr);
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void StructReturn()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public struct STATSTG {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        STATSTG CopyTo(ulong cb);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        global::Foo.STATSTG global::Foo.IStr.CopyTo(ulong cb)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            try
            {
                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                global::Foo.STATSTG retVal;
                result = ((delegate* unmanaged<System.IntPtr, ulong, global::Foo.STATSTG*, int>)vtbl[3])(thisPtr, cb, &retVal);
                if (result != 0)
                {
                    Marshal.ThrowExceptionForHR(result);
                }

                return retVal;
            }
            finally
            {
                Marshal.Release(thisPtr);
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void PreserveSigVoid()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum HRESULT {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        [PreserveSig]
        void GetWindow(System.IntPtr* phwnd);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        void global::Foo.IStr.GetWindow(global::System.IntPtr* phwnd)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            try
            {
                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                ((delegate* unmanaged<System.IntPtr, global::System.IntPtr*, void>)vtbl[3])(thisPtr, phwnd);
            }
            finally
            {
                Marshal.Release(thisPtr);
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void InParameter()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public struct STATSTG {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        void Stat(in STATSTG pstatstg);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        void global::Foo.IStr.Stat(in global::Foo.STATSTG pstatstg)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            try
            {
                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                fixed (global::Foo.STATSTG* local_0 = &pstatstg)
                result = ((delegate* unmanaged<System.IntPtr, global::Foo.STATSTG*, int>)vtbl[3])(thisPtr, local_0);
                if (result != 0)
                {
                    Marshal.ThrowExceptionForHR(result);
                }

            }
            finally
            {
                Marshal.Release(thisPtr);
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void ArrayParameter()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public struct STATSTG {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        void Stat(STATSTG[] pstatstg);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        void global::Foo.IStr.Stat(global::Foo.STATSTG[] pstatstg)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            try
            {
                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                fixed (global::Foo.STATSTG* local_0 = pstatstg)
                result = ((delegate* unmanaged<System.IntPtr, global::Foo.STATSTG*, int>)vtbl[3])(thisPtr, local_0);
                if (result != 0)
                {
                    Marshal.ThrowExceptionForHR(result);
                }

            }
            finally
            {
                Marshal.Release(thisPtr);
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void ArrayComInterfaceParameter()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public struct STATSTG {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        void Stat(IStr[] pstatstg);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        void global::Foo.IStr.Stat(global::Foo.IStr[] pstatstg)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            try
            {
                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                System.Span<System.IntPtr> local_0_arr = stackalloc System.IntPtr[pstatstg.Length == 0 ? 1 : pstatstg.Length];
                for (int local_0_cnt = 0; local_0_cnt < pstatstg.Length; local_0_cnt++)
                {
                    var arrayItem = pstatstg[local_0_cnt];
                    System.IntPtr local_0_0;
                    if (arrayItem == null)
                    {
                        local_0_0 = System.IntPtr.Zero;
                    }
                    else
                    {
                        var local_0_0_unk = MarshalSupport.GetIUnknownForObject(arrayItem);
                        var local_arrayItem_IID = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
                        result = Marshal.QueryInterface(local_0_0_unk, ref local_arrayItem_IID, out local_0_0);
                        if (result != 0)
                        {
                            Marshal.ThrowExceptionForHR(result);
                        }
                    }

                    local_0_arr[local_0_cnt] = local_0_0;
                }

                fixed (System.IntPtr* local_0 = local_0_arr)
                result = ((delegate* unmanaged<System.IntPtr, System.IntPtr*, int>)vtbl[3])(thisPtr, local_0);
                if (result != 0)
                {
                    Marshal.ThrowExceptionForHR(result);
                }

            }
            finally
            {
                Marshal.Release(thisPtr);
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void VariantReturn()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum SeekOrigin {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        object CopyTo();
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        object global::Foo.IStr.CopyTo()
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            try
            {
                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                WinFormsComInterop.InteropServices.Variant retVal;
                result = ((delegate* unmanaged<System.IntPtr, WinFormsComInterop.InteropServices.Variant*, int>)vtbl[3])(thisPtr, &retVal);
                if (result != 0)
                {
                    Marshal.ThrowExceptionForHR(result);
                }

                return MarshalSupport.GetObjectForNativeVariant((System.IntPtr)(WinFormsComInterop.InteropServices.Variant*)&retVal);
            }
            finally
            {
                Marshal.Release(thisPtr);
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void VariantOutParameter()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum SeekOrigin {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        void CopyTo(out object param);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        void global::Foo.IStr.CopyTo(out object param)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            try
            {
                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                WinFormsComInterop.InteropServices.Variant local_0;
                result = ((delegate* unmanaged<System.IntPtr, WinFormsComInterop.InteropServices.Variant*, int>)vtbl[3])(thisPtr, &local_0);
                if (result != 0)
                {
                    Marshal.ThrowExceptionForHR(result);
                }

                param = MarshalSupport.GetObjectForNativeVariant((System.IntPtr)(WinFormsComInterop.InteropServices.Variant*)&local_0);
            }
            finally
            {
                Marshal.Release(thisPtr);
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void VariantRefParameter()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum SeekOrigin {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        void CopyTo(ref object param);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        void global::Foo.IStr.CopyTo(ref object param)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            try
            {
                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                WinFormsComInterop.InteropServices.Variant local_0 = new WinFormsComInterop.InteropServices.Variant();
                Marshal.GetNativeVariantForObject(param, (System.IntPtr)(WinFormsComInterop.InteropServices.Variant*)&local_0);
                result = ((delegate* unmanaged<System.IntPtr, WinFormsComInterop.InteropServices.Variant*, int>)vtbl[3])(thisPtr, &local_0);
                if (result != 0)
                {
                    Marshal.ThrowExceptionForHR(result);
                }

                param = MarshalSupport.GetObjectForNativeVariant((System.IntPtr)(WinFormsComInterop.InteropServices.Variant*)&local_0);
            }
            finally
            {
                Marshal.Release(thisPtr);
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void VariantParameter()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum SeekOrigin {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        void CopyTo(object param);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        void global::Foo.IStr.CopyTo(object param)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            try
            {
                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                WinFormsComInterop.InteropServices.Variant local_0 = new WinFormsComInterop.InteropServices.Variant();
                Marshal.GetNativeVariantForObject(param, (System.IntPtr)(WinFormsComInterop.InteropServices.Variant*)&local_0);
                result = ((delegate* unmanaged<System.IntPtr, WinFormsComInterop.InteropServices.Variant*, int>)vtbl[3])(thisPtr, &local_0);
                if (result != 0)
                {
                    Marshal.ThrowExceptionForHR(result);
                }

            }
            finally
            {
                Marshal.Release(thisPtr);
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void NonBlittableStructParameter()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public struct STATSTG
    {
        public string Name;
        public string Desc;
    }

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IStr
    {
        void Stat(STATSTG pstatstg);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        void global::Foo.IStr.Stat(global::Foo.STATSTG pstatstg)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            try
            {
                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                STATSTG_native local_0 = default;
                var local_0_Name = pstatstg.Name;
                var local_0_0 = Marshal.StringToCoTaskMemUni(local_0_Name);
                local_0.Name = local_0_0;
                var local_0_Desc = pstatstg.Desc;
                var local_0_1 = Marshal.StringToCoTaskMemUni(local_0_Desc);
                local_0.Desc = local_0_1;
                result = ((delegate* unmanaged<System.IntPtr, STATSTG_native, int>)vtbl[3])(thisPtr, local_0);
                if (result != 0)
                {
                    Marshal.ThrowExceptionForHR(result);
                }

            }
            finally
            {
                Marshal.Release(thisPtr);
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }
    }
}
