using Microsoft.CodeAnalysis;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace WinFormsComInterop.SourceGenerator.Tests
{
    [TestClass]
    public class RuntimeCallableWrapperTest : CodeGenerationTestBase
    {
        [TestMethod]
        public void DeclarationOfProxy()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    public interface IStr
    {
        void Read(byte* pv, uint cb, uint* pcbRead);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        public void Read(byte* pv, uint cb, uint* pcbRead)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new InvalidCastException();
            }

            IntPtr* comDispatch = (IntPtr*)thisPtr;
            IntPtr* vtbl = (IntPtr*)comDispatch[0];
            ((delegate* unmanaged<IntPtr, byte*, uint, uint*, void>)vtbl[3])(thisPtr, pv, cb, pcbRead);
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }
    }
}
