using Microsoft.CodeAnalysis;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace WinFormsComInterop.SourceGenerator.Tests
{
    [TestClass]
    public class RuntimeCallableWrapperTest : CodeGenerationTestBase
    {
        [TestMethod]
        public void DeclarationOfProxy()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    public interface IStr
    {
        void Read(byte* pv, uint cb, uint* pcbRead);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        void global::Foo.IStr.Read(byte* pv, uint cb, uint* pcbRead)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            var comDispatch = (System.IntPtr*)thisPtr;
            var vtbl = (System.IntPtr*)comDispatch[0];
            result = ((delegate* unmanaged<System.IntPtr, byte*, uint, uint*, int>)vtbl[3])(thisPtr, pv, cb, pcbRead);
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void EnumParameter()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum SeekOrigin {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    public interface IStr
    {
        void Seek(long dlibMove, SeekOrigin dwOrigin, ulong* plibNewPosition);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        void global::Foo.IStr.Seek(long dlibMove, global::Foo.SeekOrigin dwOrigin, ulong* plibNewPosition)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            var comDispatch = (System.IntPtr*)thisPtr;
            var vtbl = (System.IntPtr*)comDispatch[0];
            result = ((delegate* unmanaged<System.IntPtr, long, int, ulong*, int>)vtbl[3])(thisPtr, dlibMove, (int)dwOrigin, plibNewPosition);
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void ComInterfaceParameter()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum SeekOrigin {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    public interface IStr
    {
        void CopyTo(IStr pstm, ulong cb, ulong* pcbRead, ulong* pcbWritten);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        void global::Foo.IStr.CopyTo(global::Foo.IStr pstm, ulong cb, ulong* pcbRead, ulong* pcbWritten)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            var comDispatch = (System.IntPtr*)thisPtr;
            var vtbl = (System.IntPtr*)comDispatch[0];
            var local_0_unk = Marshal.GetIUnknownForObject(pstm);
            var local_pstm_IID = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            result = Marshal.QueryInterface(local_0_unk, ref local_pstm_IID, out var local_0);
            if (result != 0)
            {
                Marshal.ThrowExceptionForHR(result);
            }

            result = ((delegate* unmanaged<System.IntPtr, System.IntPtr, ulong, ulong*, ulong*, int>)vtbl[3])(thisPtr, local_0, cb, pcbRead, pcbWritten);
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void EnumReturn()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum SeekOrigin {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    public interface IStr
    {
        SeekOrigin CopyTo(IStr pstm, ulong cb, ulong* pcbRead, ulong* pcbWritten);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        global::Foo.SeekOrigin global::Foo.IStr.CopyTo(global::Foo.IStr pstm, ulong cb, ulong* pcbRead, ulong* pcbWritten)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            var comDispatch = (System.IntPtr*)thisPtr;
            var vtbl = (System.IntPtr*)comDispatch[0];
            var local_0_unk = Marshal.GetIUnknownForObject(pstm);
            var local_pstm_IID = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            result = Marshal.QueryInterface(local_0_unk, ref local_pstm_IID, out var local_0);
            if (result != 0)
            {
                Marshal.ThrowExceptionForHR(result);
            }

            int retVal;
            result = ((delegate* unmanaged<System.IntPtr, System.IntPtr, ulong, ulong*, ulong*, int*, int>)vtbl[3])(thisPtr, local_0, cb, pcbRead, pcbWritten, &retVal);
            return (global::Foo.SeekOrigin)retVal;
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void PreserveSig()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum HRESULT {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    public interface IStr
    {
        [PreserveSig]
        HRESULT GetWindow(System.IntPtr* phwnd);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        global::Foo.HRESULT global::Foo.IStr.GetWindow(global::System.IntPtr* phwnd)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            var comDispatch = (System.IntPtr*)thisPtr;
            var vtbl = (System.IntPtr*)comDispatch[0];
            result = ((delegate* unmanaged<System.IntPtr, global::System.IntPtr*, int>)vtbl[3])(thisPtr, phwnd);
            return (global::Foo.HRESULT)result;
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void ReturnComInterface()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum HRESULT {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    public interface IStr
    {
        IStr Clone();
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        global::Foo.IStr global::Foo.IStr.Clone()
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            var comDispatch = (System.IntPtr*)thisPtr;
            var vtbl = (System.IntPtr*)comDispatch[0];
            System.IntPtr retVal;
            result = ((delegate* unmanaged<System.IntPtr, System.IntPtr*, int>)vtbl[3])(thisPtr, &retVal);
            return (global::Foo.IStr)Marshal.GetObjectForIUnknown(retVal);
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void OutParameter()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public struct STATSTG {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    public interface IStr
    {
        void Stat(out STATSTG pstatstg);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        void global::Foo.IStr.Stat(out global::Foo.STATSTG pstatstg)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            var comDispatch = (System.IntPtr*)thisPtr;
            var vtbl = (System.IntPtr*)comDispatch[0];
            fixed (global::Foo.STATSTG* local_0 = &pstatstg)
            result = ((delegate* unmanaged<System.IntPtr, global::Foo.STATSTG*, int>)vtbl[3])(thisPtr, local_0);
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void NoParameters()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum SeekOrigin {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    public interface IStr
    {
        void CopyTo();
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        void global::Foo.IStr.CopyTo()
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            var comDispatch = (System.IntPtr*)thisPtr;
            var vtbl = (System.IntPtr*)comDispatch[0];
            result = ((delegate* unmanaged<System.IntPtr, int>)vtbl[3])(thisPtr);
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void LongReturn()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum SeekOrigin {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    public interface IStr
    {
        long CopyTo(IStr pstm, ulong cb, ulong* pcbRead, ulong* pcbWritten);
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        long global::Foo.IStr.CopyTo(global::Foo.IStr pstm, ulong cb, ulong* pcbRead, ulong* pcbWritten)
        {
            var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
            if (result != 0)
            {
                throw new System.InvalidCastException();
            }

            var comDispatch = (System.IntPtr*)thisPtr;
            var vtbl = (System.IntPtr*)comDispatch[0];
            var local_0_unk = Marshal.GetIUnknownForObject(pstm);
            var local_pstm_IID = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
            result = Marshal.QueryInterface(local_0_unk, ref local_pstm_IID, out var local_0);
            if (result != 0)
            {
                Marshal.ThrowExceptionForHR(result);
            }

            long retVal;
            result = ((delegate* unmanaged<System.IntPtr, System.IntPtr, ulong, ulong*, ulong*, long*, int>)vtbl[3])(thisPtr, local_0, cb, pcbRead, pcbWritten, &retVal);
            return retVal;
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }

        [TestMethod]
        public void LongProperty()
        {
            string source = @"
namespace Foo
{
    using System.Runtime.InteropServices;

    public enum SeekOrigin {}

    [Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"")]
    public interface IStr
    {
        long Height { get; }
    }

    [RuntimeCallableWrapper(typeof(IStr))]
    partial class C
    {
    }
}";
            string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

            Assert.IsNotNull(output);

            var expectedOutput = @"// <auto-generated>
// Code generated by COM Proxy Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
using Marshal = System.Runtime.InteropServices.Marshal;

namespace Foo
{
    [System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
    unsafe partial class C : global::Foo.IStr
    {
        long global::Foo.IStr.Height
        {
            get
            {
                var targetInterface = new System.Guid(""22DD68D1-86FD-4332-8666-9ABEDEA2D24C"");
                var result = Marshal.QueryInterface(this.instance, ref targetInterface, out var thisPtr);
                if (result != 0)
                {
                    throw new System.InvalidCastException();
                }

                var comDispatch = (System.IntPtr*)thisPtr;
                var vtbl = (System.IntPtr*)comDispatch[0];
                long retVal;
                result = ((delegate* unmanaged<System.IntPtr, long*, int>)vtbl[3])(thisPtr, &retVal);
                return retVal;
            }
        }
    }
}";
            Assert.AreEqual(expectedOutput, output);
        }
    }
}
